const projects = [
  {id:1,title:'Креативная мастерская ремесла Ленинградской области',org:'АНО центр развития социальных и культурных инициатив «Ключ»',category:'Культура',territory:'Вся Ленинградская область; очный тренинг — один из районов: Ломоносовский, Приозерский или Бокситогорский',budget:958600,summary:'Программа поможет мастерам превратить традиционное ремесло в современный, заметный культурный продукт без потери его кода.',description:'Участники научатся снимать изделия и процесс работы, рассказывать истории мастерских, вести социальные сети и готовиться к ярмаркам и фестивалям. В программе — короткий онлайн-курс, чат с разбором заданий, очный тренинг и общий онлайн-каталог мастерских региона.',benefit:'Партнёр помогает сохранить локальные ремёсла и одновременно развивает малое креативное предпринимательство. Возможны совместные спецпроекты, корпоративные подарки и участие бренда в каталоге и обучающей программе.',costs:'Команда и страховые взносы — 455 600 ₽; дизайн, видео и продвижение — 183 000 ₽; эксперты — 139 000 ₽; бухгалтерия — 75 000 ₽; поездки, тренинг и материалы — 88 000 ₽; сувенирная продукция — 18 000 ₽.',post:'https://vk.ru/wall-236108312_2',presentation:'https://disk.yandex.ru/i/e5aVvyaXhx67_A',media:['https://vk.ru/album-192206244_303773506','https://vk.ru/album-192206244_306568586','https://disk.yandex.ru/i/3fskgHFdmDQyrg']},
  {id:2,title:'Расправляем паруса. Центр «Ковчег»',org:'АНО РИТКО «Творческие проекты Кайкино»',category:'Развитие территорий',territory:'д. Бегуницы, Волосовский район',budget:980000,summary:'Обустройство общественной гостиной и кухни в создаваемом жителями духовно-просветительском центре «Ковчег».',description:'В Бегуницах уже пять лет развивается центр на базе бывшего производственного здания: проведены строительные работы, подключены газ, вода и электричество. Следующий этап — оборудовать гостиную на 90 м² и кухню для семейного клуба, туристических групп, мастер-классов, встреч и круглых столов.',benefit:'Поддержка создаёт устойчивую общественную площадку в малом населённом пункте. Компания получает понятный инфраструктурный результат, связь с местным сообществом и возможность проводить на площадке собственные волонтёрские и просветительские события.',costs:'Кухонное оборудование — 765 000 ₽; столы и стулья — 100 080 ₽; монтаж — 57 420 ₽; оплата труда и страховые взносы — 57 500 ₽.',post:'https://vk.ru/wall-101412832_1367',presentation:'https://disk.yandex.ru/i/EWVUzIjc3b9kdg',media:[]},
  {id:3,title:'Отдельный батальон',org:'АНО «Культурный мост»',category:'Образование',territory:'д. Низино, Ломоносовский район',budget:924450,summary:'Многофункциональный учебно-тренировочный комплекс для практических занятий по технической, тактической и первой помощи.',description:'Проект создаст современную учебную базу: VR-очки для симуляции полётов, компьютеры, FPV-дроны разных классов, 3D-принтер для деталей, а также оснащение для огневой, инженерной, тактической, медицинской подготовки и РХБЗ.',benefit:'Партнёр вкладывается в прикладные технические навыки молодёжи и получает возможность поддержать оснащение конкретных учебных направлений. Особенно органично участие технологических, производственных и инженерных компаний.',costs:'Дроновая подготовка — 445 000 ₽; огневая — 170 600 ₽; инженерная — 144 000 ₽; экипировка — 132 800 ₽; тактическая, медицинская подготовка и РХБЗ — 32 050 ₽.',post:'https://vk.ru/wall-185289670_788',presentation:'https://disk.yandex.ru/i/jUaA_R27QyeFrg',media:['https://vkvideo.ru/video-205421203_456239211?list=b56bc0bd4535417f97']},
  {id:4,title:'СВОЯ лига ВОИ: творческая лаборатория возможностей',org:'АНО «Ленинградское областное объединение команд КВН инвалидов “СВОЯ лига”»',category:'Инклюзия',territory:'Ленинградская область, Тихвинский район; мероприятия также в Санкт-Петербурге, Альметьевске и Сочи',budget:980000,summary:'Инклюзивная творческая лаборатория на базе единственной в России официальной лиги КВН, где играют команды людей с инвалидностью.',description:'За 11 лет в «СВОЕЙ лиге ВОИ» участвовали 135 команд из 40 регионов России, Беларуси и Казахстана. Проект создаст и запустит модель лаборатории, объединяющей обучение, авторские сборы, выступления и тиражирование лучших практик в других регионах.',benefit:'Яркое партнёрство с широкой географией и живым публичным форматом. Бизнес поддерживает инклюзию без формального тона и может участвовать в событиях, обучении, поездках сборной и развитии тиражируемой модели.',costs:'Обучающие мероприятия — 140 000 ₽; участие в фестивале «КиВиН» — 375 000 ₽; финал КВН ВОИ — 287 000 ₽; участие в Центральной лиге «Поволжье» — 178 000 ₽.',post:'https://vk.ru/wall25567152_9317',presentation:'https://disk.yandex.ru/i/5T08q1QJeWieCQ',media:['https://disk.yandex.ru/d/EjRz-mkNyW7low']},
  {id:5,title:'Тёплые лапы',org:'АНО «Социальная кинологическая помощь»',category:'Забота',territory:'Выборгский и Лодейнопольский районы',budget:148080,summary:'Выездные новогодние встречи с далматинами-терапевтами для пациентов хосписа и пожилых людей в интернате.',description:'Команда проведёт тёплую интерактивную программу с собаками-терапевтами и подарками в хосписе Выборга и интернате для пожилых людей в Лодейном Поле. Проект адресно поддерживает людей, которым особенно не хватает общения и положительных эмоций.',benefit:'Небольшой бюджет позволяет профинансировать проект целиком и получить быстрый, понятный человеческий результат. Подходит для корпоративного волонтёрства, адресной помощи и праздничной программы от компании.',costs:'Оплата труда и страховые взносы — 52 080 ₽; работы и услуги — 74 000 ₽; оборудование — 7 000 ₽; транспорт — 15 000 ₽.',post:'https://vk.ru/wall-231685801_454',presentation:'https://disk.yandex.ru/i/4BYWf7hSW7_NvQ',media:['https://vk.ru/wall-231685801_467']},
  {id:6,title:'Иоанновский дом',org:'Социальный центр помощи детям и приёмным семьям «Иоанновский дом»',category:'Семья и дети',territory:'Всеволожский, Выборгский, Приозерский и Тосненский районы',budget:2000000,summary:'Постоянная профессиональная поддержка приёмных семей, детей в трудной ситуации и молодых выпускников детских домов.',description:'Центр сопровождает семью от окончания школы приёмных родителей до сложного первого года адаптации ребёнка. Здесь также обучают наставников для выпускников детских домов и поддерживают бабушек и дедушек, воспитывающих внуков вместо родителей.',benefit:'Компания обеспечивает непрерывную работу специалистов, от которых напрямую зависит устойчивость семей. Партнёрство даёт долгосрочный социальный эффект в четырёх районах и может включать волонтёрство сотрудников и поддержку наставничества.',costs:'Запрашиваемые средства направляются на оплату работы двух педагогов-психологов, администратора и бухгалтера центра.',post:'https://vk.ru/club233694605?w=wall-233694605_236',presentation:'https://disk.yandex.ru/i/xmQkzF9yylH2CQ',media:['https://disk.yandex.ru/d/_W4tkEqxZponPA']},
  {id:7,title:'Новая жизнь',org:'Футбольный клуб инвалидов «Олимпия-Тихвин»',category:'Спорт',territory:'п. Царицыно Озеро, Тихвинский район',budget:979292.67,summary:'Ремонт единственной в регионе доступной спортивной базы для людей с поражением опорно-двигательного аппарата.',description:'Проект сделает базу безопасной для тренировок, соревнований и сборов: расширит дверные проёмы, установит поручни, заменит полы и санузлы. Пространство уже объединяет людей с инвалидностью вокруг спорта и реабилитации.',benefit:'Вклад превращается в конкретный, видимый и долговечный объект доступной среды. Компания может поддержать отдельный этап ремонта, предоставить материалы или привлечь сотрудников к благоустройству.',costs:'Строительные материалы и ремонтные работы — 974 292,67 ₽; канцелярские товары — 5 000 ₽.',post:'https://vk.ru/wall28686046_3592',presentation:'https://disk.yandex.ru/i/cJl3GgYYYnbumw',media:['https://disk.yandex.ru/i/gD2ZdWWNuw_EMQ']},
  {id:8,title:'Клуб гатчинских зооволонтёров',org:'АНО «Социальный центр спасения и реабилитации животных “Альтера Вита”»',category:'Животные',territory:'Гатчинский муниципальный округ',budget:969190,summary:'Системная поддержка волонтёров и жителей, которые помогают бездомным животным в Гатчинском округе.',description:'Участники получат бесплатную стерилизацию кошек, корма и препараты, перевозку животных в клинику, консультации зоопсихолога и фотографа, а также помощь в поиске дома. Проект поддерживает не только животных, но и людей, которые ежедневно о них заботятся.',benefit:'Партнёр помогает выстроить системное решение заметной городской проблемы. Возможны денежная помощь, поставки кормов и препаратов, транспортная поддержка, участие сотрудников и совместные кампании ответственного отношения к животным.',costs:'Ветеринарные услуги — 350 000 ₽; команда и страховые взносы — 449 190 ₽; бухгалтерское сопровождение — 170 000 ₽.',post:'https://vk.ru/wall-226783052_1516',presentation:'https://disk.yandex.ru/i/jtWUdGDm_Hc5yg',media:[]},
  {id:9,title:'Мастерская новых возможностей 3.0',org:'Благотворительный фонд «Место под солнцем»',category:'Инклюзия',territory:'Подпорожский, Кингисеппский и Выборгский районы',budget:845000,summary:'Работа мастерских социальной занятости для молодых людей с ментальными и двигательными нарушениями в трёх районах.',description:'Двадцать участников будут создавать сувенирную продукцию к 100-летию Ленинградской области и получать вознаграждение по 10 000 рублей в месяц в течение трёх месяцев. Финансирование обеспечит материалы, производство и реальную оплачиваемую занятость.',benefit:'Бизнес поддерживает не разовое мероприятие, а трудовую включённость молодых людей с инвалидностью. Возможны заказы корпоративных сувениров, помощь материалами, наставничество и совместное продвижение продукции мастерских.',costs:'Расходные материалы и изготовление сувенирной продукции; вознаграждение 20 участникам мастерских по 10 000 ₽ в месяц с октября по декабрь 2026 года.',post:'https://vk.ru/wall-53484554_5426',presentation:'https://disk.yandex.ru/i/2gyIRPNWoctHwQ',media:['https://vkvideo.ru/video-176829672_456239205?c=1','https://vk.ru/wall-53484554_5048']},
  {id:10,title:'деЛО будущего',org:'АНО «Продюсерский центр Полины Тумашик»',category:'Образование',territory:'Волховский, Тосненский, Ломоносовский, Всеволожский и Выборгский районы',budget:481000,summary:'Профориентационная программа для 300 подростков, в которой бизнес помогает увидеть реальную картину современных профессий.',description:'Вместе с предпринимателями команда создаст шесть видеоподкастов и рабочую тетрадь «6 ключей для карьеры». Подростки отработают навыки на практике и смогут выбрать следующий шаг, а представители компаний выступят интеллектуальными волонтёрами.',benefit:'Прямая инвестиция в будущие кадры региона. Компания может представить свои профессии, дать экспертов для подкастов, познакомиться с мотивированными подростками и получить измеримый охват в пяти районах.',costs:'Команда проекта и страховые взносы — 346 000 ₽; съёмка шести видеоподкастов — 60 000 ₽; печать рабочих тетрадей — 75 000 ₽.',post:'https://vk.ru/wall-145072342_682',presentation:'https://disk.yandex.ru/i/xR1LTMsW57lkjA',media:['https://disk.yandex.ru/d/APSnK4N7RfmoYw']},
  {id:11,title:'Добрый круг профессий',org:'Благотворительный фонд «Вера и надежда»',category:'Семья и дети',territory:'Тосненский район',budget:935055,summary:'Практическая профориентация для 30 подростков из семей в трудной жизненной ситуации.',description:'Подростки 10–17 лет пройдут мастерские по столярному и слесарному делу, познакомятся с основами электрики, посетят колледжи и предприятия. Проект развивает практические навыки, ответственность и интерес к востребованным рабочим профессиям.',benefit:'Производственная компания может не только профинансировать проект, но и открыть подросткам реальные рабочие места: провести экскурсию, дать наставников, материалы или оборудование. Это ранняя профориентация и вклад в кадровый резерв территории.',costs:'Аренда помещения — 385 000 ₽; оплата труда и страховые взносы — 311 040 ₽; пять столярных верстаков — 150 000 ₽; инструменты и материалы — 89 015 ₽.',post:'https://vk.ru/wall-79116430_5166',presentation:'https://disk.yandex.ru/i/BnRTl4ygG3qkvg',media:[]},
  {id:12,title:'Лошадь в истории — история лошади',org:'ЛООО «Конно-спортивный клуб “Новополье”»',category:'Образование',territory:'д. Новополье, Ломоносовский район',budget:978952,summary:'Интерактивные экскурсии для младших школьников, соединяющие историю, творчество и безопасное общение с лошадьми.',description:'Ученики 3–5 классов Ломоносовского района смогут проводить полезный образовательно-познавательный досуг в конно-спортивном клубе: узнавать историю через живое взаимодействие с лошадью, участвовать в арт-терапии и совместном чаепитии.',benefit:'Партнёр поддерживает доступный познавательный досуг детей и развитие локальной площадки. Возможны финансирование групп, благоустройство территории, помощь кормами и корпоративные волонтёрские дни.',costs:'Команда и страховые взносы — 313 952 ₽; материалы для благоустройства и корма — 351 000 ₽; чаепития — 86 000 ₽; аренда спецтехники — 84 000 ₽; ипповент — 80 000 ₽; арт-терапевт — 64 000 ₽.',post:'https://vk.ru/wall-3307486_12019',presentation:'https://disk.yandex.ru/i/4UEykKdpSdYjaA',media:['https://disk.yandex.ru/i/GMwl21pJiinFbg']}
];

const formatMoney = value => new Intl.NumberFormat('ru-RU', {style:'currency',currency:'RUB',maximumFractionDigits:value % 1 ? 2 : 0}).format(value);
const categories = ['Все', ...new Set(projects.map(p => p.category))];
const state = { category:'Все', query:'', shortlist:new Set(JSON.parse(localStorage.getItem('nkoShortlist') || '[]')), shortlistOnly:false };
const grid = document.getElementById('projectGrid');
const filters = document.getElementById('filters');
const modal = document.getElementById('projectModal');

function persist(){ localStorage.setItem('nkoShortlist', JSON.stringify([...state.shortlist])); }
function updateCount(){ document.getElementById('shortlistCount').textContent = state.shortlist.size; }
function renderFilters(){ filters.innerHTML = categories.map(c => `<button class="filter ${state.category===c?'active':''}" type="button" data-category="${c}">${c}</button>`).join(''); }
function projectImage(p){
  if (p.id === 2) return 'project-02.png';
  if (p.id === 3) return 'project-03.jpeg';
  if (p.id === 5) return 'project-05.jpeg';
  if (p.id === 6) return 'project-06.webp';
  if (p.id === 8) return 'project-08.png';
  if (p.id === 10) return 'project-10.png';
  if (p.id === 12) return 'project-12.png';
  return window.projectImages[p.id];
}
function card(p){ const saved=state.shortlist.has(p.id); return `<article class="project-card" data-card-open="${p.id}" tabindex="0" aria-label="Открыть проект «${p.title}»">
  <div class="card-visual"><img src="${projectImage(p)}" alt="Материалы проекта «${p.title}»" loading="lazy"><div class="card-shade"></div><div class="card-overlay"><span class="tag">${p.category}</span><h3>${p.title}</h3></div><button class="save ${saved?'saved':''}" type="button" data-save="${p.id}" aria-label="${saved?'Убрать из выбора':'Добавить в выбор'}" aria-pressed="${saved}">${saved?'★':'☆'}</button></div>
  <p class="territory">${p.territory}</p><p class="summary">${p.summary}</p>
  <div class="card-foot"><div><span class="budget-label">Запрашиваемая сумма</span><span class="budget">${formatMoney(p.budget)}</span></div><button class="more" type="button" data-open="${p.id}">Подробнее →</button></div>
  </article>`; }
function filtered(){ const q=state.query.trim().toLowerCase(); return projects.filter(p => (!state.shortlistOnly || state.shortlist.has(p.id)) && (state.category==='Все'||p.category===state.category) && (!q || [p.title,p.org,p.territory,p.summary,p.category].join(' ').toLowerCase().includes(q))); }
function render(){ const items=filtered(); grid.innerHTML=items.map(card).join(''); document.getElementById('resultsMeta').textContent=`Показано проектов: ${items.length} из ${projects.length}`; document.getElementById('emptyState').hidden=items.length>0; updateCount(); renderFilters(); document.getElementById('shortlistButton').setAttribute('aria-pressed',state.shortlistOnly); document.getElementById('shortlistButton').classList.toggle('active',state.shortlistOnly); }
function toggleSave(id){ state.shortlist.has(id)?state.shortlist.delete(id):state.shortlist.add(id); persist(); render(); const openId=Number(modal.dataset.project); if(!modal.hidden && openId===id) openProject(id); }
function openProject(id){ const p=projects.find(x=>x.id===id); if(!p)return; modal.dataset.project=id; document.getElementById('modalContent').innerHTML=`
  <div class="modal-visual"><img src="${projectImage(p)}" alt="Материалы проекта «${p.title}»"></div>
  <p class="modal-kicker"><span>Проект ${String(p.id).padStart(2,'0')}</span><span class="tag">${p.category}</span></p>
  <h2 id="modalTitle">${p.title}</h2><p class="modal-territory">${p.territory}</p>
  <p class="modal-lead">${p.description}</p><section class="benefit"><h3>Что получает бизнес</h3><p>${p.benefit}</p></section>
  <div class="detail-grid"><section class="detail-block"><h3>Запрашиваемая сумма</h3><p class="big">${formatMoney(p.budget)}</p></section><section class="detail-block"><h3>Организация</h3><p>${p.org}</p></section><section class="detail-block full"><h3>На что нужны средства</h3><p>${p.costs}</p></section></div>
  <div class="links"><a class="resource-link" href="${p.presentation}">Открыть презентацию →</a><a class="resource-link secondary" href="${p.post}">Пост о проекте →</a>${p.media.map((u,i)=>`<a class="resource-link secondary" href="${u}">${p.media.length>1?'Материал '+(i+1):'Фото и видео'} →</a>`).join('')}</div>
  <button class="modal-save" type="button" data-save="${p.id}">${state.shortlist.has(p.id)?'★ В моём выборе':'☆ Добавить в мой выбор'}</button>`;
  modal.hidden=false; document.body.classList.add('modal-open'); setTimeout(()=>document.querySelector('.modal-close').focus(),0); }
function closeModal(){ modal.hidden=true; document.body.classList.remove('modal-open'); delete modal.dataset.project; }

filters.addEventListener('click',e=>{const b=e.target.closest('[data-category]');if(!b)return;state.category=b.dataset.category;render();});
grid.addEventListener('click',e=>{const s=e.target.closest('[data-save]');if(s){toggleSave(Number(s.dataset.save));return;}const o=e.target.closest('[data-open]');if(o){openProject(Number(o.dataset.open));return;}const card=e.target.closest('[data-card-open]');if(card)openProject(Number(card.dataset.cardOpen));});
grid.addEventListener('keydown',e=>{if(e.key!=='Enter'&&e.key!==' ')return;if(e.target.closest('button,a'))return;const card=e.target.closest('[data-card-open]');if(!card)return;e.preventDefault();openProject(Number(card.dataset.cardOpen));});
document.getElementById('modalContent').addEventListener('click',e=>{const s=e.target.closest('[data-save]');if(s)toggleSave(Number(s.dataset.save));});
document.querySelectorAll('[data-close-modal]').forEach(x=>x.addEventListener('click',closeModal));
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!modal.hidden)closeModal();});
document.getElementById('searchInput').addEventListener('input',e=>{state.query=e.target.value;render();});
document.getElementById('shortlistButton').addEventListener('click',()=>{state.shortlistOnly=!state.shortlistOnly;render();document.querySelector('.catalog').scrollIntoView({behavior:'smooth'});});
document.getElementById('resetButton').addEventListener('click',()=>{state.category='Все';state.query='';state.shortlistOnly=false;document.getElementById('searchInput').value='';render();});
render();
